### ISSUE TITLE
Which operating systems supported?

### ISSUE THREAD

**Issue by StudioMaX** [dr-bonez/tor-v3-vanity#1]
I wanted to try your project, but I ran into a error without even compiling it yet. The question may seem rather stupid, but in the description I did not find the answer anywhere which operating systems are supported.

So which operating systems are supported? Is Windows supported?

Some logs when I tried to compile this on my Windows 10 2004:

> $ cargo install --path .
>   Installing tor-v3-vanity v0.1.0 (E:\Projects\tor-v3-vanity)
>     Updating crates.io index
>    Compiling tor-v3-vanity v0.1.0 (E:\Projects\tor-v3-vanity)
> error: failed to compile `tor-v3-vanity v0.1.0 (E:\Projects\tor-v3-vanity)`, intermediate artifacts can be found at `E:\Projects\tor-v3-vanity\target`
> 
> Caused by:
>   failed to run custom build command for `tor-v3-vanity v0.1.0 (E:\Projects\tor-v3-vanity)`
> 
> Caused by:
>   process didn't exit successfully: `E:\Projects\tor-v3-vanity\target\release\build\tor-v3-vanity-53684813979faf30\build-script-build` (exit code: 1)
> --- stdout
> cargo:rustc-link-search=native=/usr/local/cuda/lib64/
> 
> --- stderr
> [PTX] Unable to build a PTX crate!
> [PTX] warning: unused manifest key: build
> [PTX]    Compiling proc-macro2 v1.0.19
> [PTX]    Compiling unicode-xid v0.2.1
> [PTX]    Compiling syn v1.0.36
> [PTX]    Compiling byteorder v1.3.4
> [PTX]    Compiling rustacuda_core v0.1.2
> [PTX]    Compiling ed25519-compact v0.1.6
> [PTX] error[E0463]: can't find crate for `core`
> [PTX]   |
> [PTX]   = note: the `nvptx64-nvidia-cuda` target may not be installed
> [PTX]
> [PTX] error: aborting due to previous error
> [PTX]
> [PTX] For more information about this error, try `rustc --explain E0463`.
> [PTX] error: could not compile `ed25519-compact`.
> [PTX]
> [PTX] warning: build failed, waiting for other jobs to finish...
> [PTX] error[E0463]: can't find crate for `core`
> [PTX]   |
> [PTX]   = note: the `nvptx64-nvidia-cuda` target may not be installed
> [PTX]
> [PTX] error: aborting due to previous error
> [PTX]
> [PTX] For more information about this error, try `rustc --explain E0463`.
> [PTX] error: build failed

**Comment by dr-bonez** [comment]
This project unfortunately only works for Linux. It may be possible to run on WSL, however, as NVIDIA has released a cuda toolkit for it. I have not tested it though, so I'm not confident it will be easy.

**Comment by dr-bonez** [comment]
That said the error you are having right now is because I forgot to add a step in my readme. Just added it. `rustup target add nvptx64-nvidia-cuda`
