### ISSUE TITLE
[FR] Checkpoint support

### ISSUE THREAD

**Issue by Diniboy1123** [dr-bonez/tor-v3-vanity#3]
Hi,

I just found this project and it seems to be amazing. However I would like to request a feature to periodically save a checkpoint to the disk so the generator doesn't have to start from the beginning always if an unexpected system crash or power outage happens, but can continue from the last saved step. Would that be possible to implement?

Thanks

**Comment by dr-bonez** [comment]
So, I'm not sure what you mean. Every time it starts, it generates a random 256 bit integer for each device and starts counting from there. This is all probabilistic so there is no such thing as "progress". If your system crashes, you can simply start it over again, and it will not affect the expected time to completion.

**Comment by Diniboy1123** [comment]
Oh I see. Then there is no way to pick up the previous session's progress.
